# Basic configuration file
#---------------------------
# This configuration file is intended to be used as a basic example and test
# dataset for the KAPy suite. It is loosely based on the configuration used in the
# Ghana Climate Atlas, but with simplifications to make it run faster. Sample datasets
# can be downloaded from https://download.dmi.dk/Research_Projects/KAPy/
# For instructions, see 
kapy:
    configurationTables:
        inputs:  'config/inputs.tsv'
        indicators: 'config/indicators.tsv'
        #    calibration: 'config/calibration.tsv'
        periods:  'config/periods.tsv'
        seasons: 'config/seasons.tsv'
    dirs:
        variables: 'outputs/1.variables'
        calibration: 'outputs/2.calibration'
        indicators: 'outputs/3.indicators'
        regridded: 'outputs/4.commmon_grid'
        ensstats: 'outputs/5.ensstats'
        arealstats: 'outputs/6.areal_statistics'
        plots: 'outputs/7.plots'

    # Configuration options------------------------------------
    arealstats:
        useAreaWeighting: True
        shapefile: ''
        idColumn: ''
        #shapefile: 'docs/tutorials/Tutorial05_files/Ghana_regions.shp'
        #idColumn: 'ADM1_PCODE'
    cutouts:
        method: 'none'
        #method: 'lonlatbox'
        #xmin: -4
        #xmax: 2
        #ymin: 4
        #ymax: 12
    ensembles:
        upperPercentile: 90
        centralPercentile: 50
        lowerPercentile: 10
    outputGrid:
        #regriddingEngine: 'none'
        regriddingEngine: 'cdo'
        gridName: 'Ghana025'
        cdoGriddes: 'config/griddes.txt'
    processing:
        picklePrimaryVariables: True
        
input_json: "config/testcase_2.json"
mmd_output: "/home/shamlym/workspace/klima-kverna/new/klima/outputs/testcase_2/mmd"
nc_output: "/home/shamlym/workspace/klima-kverna/new/klima/outputs/testcase_2"
input_base: "/home/shamlym/workspace/klima-kverna/nc/"